name: Rust

on:
  push:
    branches: [ main, develop ]
  pull_request:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manually triggered'

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Install toolchains
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src, rustfmt
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: ["nanos", "nanox", "nanosplus"]

    env:
      OBJCOPY: arm-none-eabi-objcopy
      NM: arm-none-eabi-nm

    steps:
      - name: arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1.0.3
        with:
          release: '9-2019-q4'
      - name: Install toolchains
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src, clippy
      - uses: actions/checkout@v3
      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -Z build-std=core -Z build-std-features=compiler-builtins-mem --target ./rsdk/${{ matrix.target }}.json
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["nanos", "nanox", "nanosplus"]

    env:
      OBJCOPY: arm-none-eabi-objcopy
      NM: arm-none-eabi-nm

    steps:
      - name: arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1.0.3
        with:
          release: '9-2019-q4'
      - name: Install clang
        run: sudo apt-get update && sudo apt install -y clang
      - name: Install toolchains
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout SDK (targets)
        uses: actions/checkout@v3
        with:
          repository: 'alamgu/ledger-nanos-sdk'
          ref: memory-fixes
          path: rsdk
      - run: echo "/rsdk/scripts" >> $GITHUB_PATH
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -Z build-std=core -Z build-std-features=compiler-builtins-mem --target ./rsdk/${{ matrix.target }}.json

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["nanos", "nanox", "nanosplus"]

    env:
      OBJCOPY: arm-none-eabi-objcopy
      NM: arm-none-eabi-nm

    steps:
      - name: arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1.0.3
        with:
          release: '9-2019-q4'
      - name: Install clang
        run: sudo apt-get update && sudo apt install -y clang
      - name: Install toolchains
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src
      - run: echo "$PWD/scripts" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y qemu-user-static
          pip install speculos --extra-index-url https://test.pypi.org/simple/
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout SDK (targets)
        uses: actions/checkout@v3
        with:
          repository: 'alamgu/ledger-nanos-sdk'
          ref: memory-fixes
          path: rsdk
      - run: echo "/rsdk/scripts" >> $GITHUB_PATH
      - name: Unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -Z build-std=core -Z build-std-features=compiler-builtins-mem --target ./rsdk/${{ matrix.target }}.json
